### ISSUE TITLE
Create collections

### ISSUE THREAD

**Issue by jhelguero** [maguero/planning-poker#20]
Create Story Session collection
Create Planning Session collection
Populate with some data as example 

Collections model
[Collections.txt](https://github.com/maguero/planning-poker/files/1986137/Collections.txt)

**Comment by jhelguero** [comment]
[Collections.txt](https://github.com/maguero/planning-poker/files/1986135/Collections.txt)

**Comment by jhelguero** [comment]
Add allVoted (true | false) as attribute to Planning session collection.

**Comment by ehernand** [comment]
AllVoted and storyPoints have been added
