### ISSUE TITLE
Planning room - Create Planning room component/page

### ISSUE THREAD

**Issue by maguero** [maguero/planning-poker#5]
- [x] Integrate boostrap
- [x] Create placeholder for each section
- [x] Include planning room into app.component

**Comment by jhelguero** [comment]
How to integrate boostrap into our project:

npm install --save bootstrap@next
@import "~bootstrap/dist/css/bootstrap.css" into style.css

Documentation

https://getbootstrap.com/docs/4.0/examples/

**Comment by maguero** [comment]
> npm install bootstrap@4.0.0-beta.2 --save

No hay drama con usar una version beta?
